### ISSUE TITLE
ImportError: cannot import name 'structref'

### ISSUE THREAD

**Issue by slgero** [retentioneering/retentioneering-tools#44]
Hello, how can I solve this problem?

```python
>>> pip3 install retentioneering
>>> import retentioneering

<<< ImportError: cannot import name 'structref'
```

**Comment by ChernyshovAnton** [comment]
At the end of April 2023, we will be moving to the version 3 of the library. 
You can use pip to install packages into your beta version:
pip install retentioneering --pre
This problem is not relevant in the new major version.
Documentation is available [here](https://doc.retentioneering.com/release3/doc/).
