### ISSUE TITLE
ValueError on seaborn==0.11.2

### ISSUE THREAD

**Issue by SvetoforColumb** [retentioneering/retentioneering-tools#53]
Cell

```
data.rete.compare(groups=(test, control),
                  function=conversion,
                  test='mannwhitneyu',
                  group_names=('test','control'))'
```

 in [tutorial](https://retentioneering.github.io/retentioneering-tools/_build/html/compare.html) doesn't work and fails with `ValueError: cannot reindex on an axis with duplicate labels` error.
After downgrading to seaborn==0.11.1 error dissapear.

**Comment by ChernyshovAnton** [comment]
At the end of April 2023, we will be moving to the version 3 of the library. You can use pip to install packages into your beta version:
`pip install retentioneering --pre`
The Compare tool is now called Stattest. Documentation on the tool is available for version 3:
[User guide](https://doc.retentioneering.com/release3/doc/user_guides/stattests.html) 
[API Reference](https://doc.retentioneering.com/release3/doc/api/tooling/stattests.html)
This problem is not relevant in the new major version.
