### ISSUE TITLE
Strange results in StepSankey variable time_to_next_sum

### ISSUE THREAD

**Issue by AnastasiiaTrimasova** [retentioneering/retentioneering-tools#63]
Seems like time_to_next_sum in  StepSankey graph edges contain incorrect negative values, which I could calculate correctly myself using python and same dataset. 

<img width="300" alt="Screenshot 2024-07-30 at 15 54 54" src="https://github.com/user-attachments/assets/484aec5f-9e96-4e30-95d0-da5c9cc72171">

**Comment by wowone** [comment]
@AnastasiiaTrimasova 
Looks like this issue was discussed later here: https://t.me/retentioneering_support/2936
We won't be able to fix it soon. As a dummy workaround we suggest to calculate correct time distances like the this: https://colab.research.google.com/drive/1wSPjO_aCINNlilshtiCA7cQySRZgbKSY?usp=sharing

**Comment by AnastasiiaTrimasova** [comment]
@wowone thanks for the answer! Yes, I used my own workaround, good to know you are aware of this behavior =)
